apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: example-configmap-1
    files:
      - application.properties
commonAnnotations:
  oncallPager: 800-555-1212
labels:
  - pairs:
      project: "1234"

patches:
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test
      spec:
        storageClassName:
        resources:
          requests:
            storage: 20Gi

patchesJSON6902:
  - target: { version: v1, kind: PersistentVolumeClaim, name: test }
    patch: |-
      - op: replace
        path: /spec/accessModes/0
        value: ReadWriteMany

resources:
  - pvc.yml
